base_images:
  govulncheck:
    name: govulncheck
    namespace: ci
    tag: latest
  os:
    name: centos
    namespace: openshift
    tag: stream9
  sonar:
    name: sonar-scanner-alpine
    namespace: ci
    tag: latest
  tools:
    name: "4.16"
    namespace: ocp
    tag: tools
binary_build_commands: make
build_root:
  from_repository: true
images:
- dockerfile_path: images/release-controller/Dockerfile
  from: tools
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/release-controller/release-controller
  to: release-controller
- dockerfile_path: images/release-controller-api/Dockerfile
  from: tools
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/release-controller/release-controller-api
  to: release-controller-api
- dockerfile_path: images/release-payload-controller/Dockerfile
  from: os
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/release-controller/release-payload-controller
  to: release-payload-controller
- dockerfile_path: images/release-reimport-controller/Dockerfile
  from: tools
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/release-controller/release-reimport-controller
  to: release-reimport-controller
promotion:
  to:
  - namespace: ci
    tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make test
  container:
    from: src
- as: govulncheck
  commands: GOCACHE=$(mktemp -d) GOMODCACHE=$(mktemp -d) govulncheck ./...
  container:
    from: govulncheck
  optional: true
- as: security
  optional: true
  steps:
    env:
      PROJECT_NAME: openshift/release-controller
    workflow: openshift-ci-security
- as: sonar
  cluster: build05
  commands: |
    sonar-scanner -X -Dsonar.token=$(cat /usr/local/tokens/release-controller)
  container:
    from: sonar
  secrets:
  - mount_path: /usr/local/tokens
    name: openshift-crt-sonar-tokens
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release-controller
