base_images:
  commitchecker:
    name: commitchecker
    namespace: ci
    tag: "4.15"
  ocp_4.18_base-rhel9:
    name: "4.18"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.22-openshift-4.18:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.18
build_root:
  from_repository: true
images:
- dockerfile_path: openshift/operator-controller.Dockerfile
  inputs:
    ocp_4.18_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.18:base-rhel9
    ocp_builder_rhel-9-golang-1.22-openshift-4.18:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18
  to: olm-operator-controller
promotion:
  to:
  - name: "4.18"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.18"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.18"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: mkdir -p /usr/local/bin && curl -Lfso /usr/local/bin/jq
  https://github.com/stedolan/jq/releases/download/jq-1.7.1/jq-linux64 && chmod +x
  /usr/local/bin/jq
tests:
- as: unit
  commands: make test-unit
  container:
    from: src
- as: verify
  commands: make -C openshift verify
  container:
    from: src
- as: verify-deps
  commands: |
    # Verify main repo deps
    make -f openshift/Makefile verify-deps
    # Verify openshift dir
    cd openshift && make verify-deps
  container:
    from: src
- as: verify-commits
  commands: commitchecker --start ${PULL_BASE_SHA:-main}
  container:
    from: commitchecker
- as: openshift-e2e-aws-techpreview
  skip_if_only_changed: ^docs/|\.md$|^(?:.*\/)?(?:\.gitignore|DOWNSTREAM_OWNERS|DOWNSTREAM_OWNERS_ALIASES|LICENSE|DCO|CODEOWNERS)|\.golangci\.yaml|\.goreleaser\.yml|\.markdownlint.yaml|^\.github|Tiltfile$
  steps:
    cluster_profile: aws
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    test:
    - as: upstream-e2e
      commands: make -C openshift test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: check-sync-pr-valid
  commands: |
    if [ "$(curl -sSL "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues/${PULL_NUMBER}" |jq -e '.labels[] | select(.name=="kind/sync") |.name' | wc -l )" -gt 0 ]; then
      remote_base_latest_commit=$(git ls-remote --exit-code -q --refs git@github.com:${REPO_OWNER}/${REPO_NAME}.git refs/heads/${PULL_BASE_REF} | cut -f1)
      if [! $(git merge-base --is-ancestor "${remote_base_latest_commit}" HEAD) ]; then
        echo "missing commit ${remote_base_latest_commit} from branch ${PULL_HEAD_REF}: branch needs rebase on base branch ${PULL_BASE_REF}";
        exit 1;
      fi
    fi
  container:
    from: test-bin
zz_generated_metadata:
  branch: main
  org: openshift
  repo: operator-framework-operator-controller
